name: Simple GitHub Action Demo

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        # uses: actions/checkout@v2 # is to checkout tag: v2
        uses: actions/checkout@main

      - name: Set up environment
        run: |
          pip install --upgrade pip
          python3 -m venv env 
          source env/bin/activate
          echo "VIRTUAL ENV: " $VIRTUAL_ENV
          python -m pip install pytest
          python -m pip install pytest-cov
      
      - name: Test and create coverage report
        run: | 
          pip list
          python project.py
          # pytest --cov --cov-report term --cov-report xml:coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
