name: Simple GitHub Action Demo

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        # uses: actions/checkout@v2 # is to checkout tag: v2
        uses: actions/checkout@main

      # - name: Print a message
        # run: ls
      
      - name: Execute script
        run: python project.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
