name: Simple GitHub Action Demo

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print a message
        run: ls
      
      - name: Execute script
        run: project.py
